Null safety
sonikro/flutter-okta-sdk pull request #23
Opened 2021-05-17 07:14 UTC by chaitanya-bhagavan

2021-05-20 13:48 UTC, sonikro commented
Thanks for the PR @chaitanya-bhagavan. I don't know swift myself, so I'll try to find someone else to review this PR, since I don't have the necessary knowledge to judge this code. Could you please describe this PR a little better? What is this fixing/improving ?

2021-05-20 13:54 UTC, sonikro commented
Also, I see you're updating the flutter dependency to minimum 2.0. I think this is a breaking change, since people will be forced to update their flutter version to use the library. If this gets merged, we have to release version 2.0.0 and document the breaking change (note for future self)

2021-05-20 14:00 UTC, maiconpeixinho requested changes

2021-05-20 14:00 UTC, maiconpeixinho commented on ios/Classes/SwiftFlutterOktaSdkPlugin.swift
> +      return;
Is it really required to have a 'return' here since we are calling the callback?

2021-05-20 14:00 UTC, maiconpeixinho commented on ios/Classes/SwiftFlutterOktaSdkPlugin.swift
> +      return
Is it really required to have a 'return' here since we are calling the callback?

2021-05-20 14:00 UTC, maiconpeixinho commented on ios/Classes/SwiftFlutterOktaSdkPlugin.swift
> +      return
Is it really required to have a 'return' here since we are calling the callback?

2021-05-20 16:01 UTC, Perdiga commented
> Also, I see you're updating the flutter dependency to a minimum 2.0. I think this is a breaking change since people will be forced to update their flutter version to use the library. If this gets merged, we have to release version 2.0.0 and document the breaking change (note for future self)

Do we need to increase the minimum, I think that we can keep the same version. But if we decide to update it will be a breaking change

2021-05-21 04:58 UTC, chaitanya-bhagavan commented
> > Also, I see you're updating the flutter dependency to a minimum 2.0. I think this is a breaking change since people will be forced to update their flutter version to use the library. If this gets merged, we have to release version 2.0.0 and document the breaking change (note for future self)
> 
> Do we need to increase the minimum? I think that we can keep the same version. But if we decide to update it will be a breaking change

Reverted to 1.20

2021-05-21 10:44 UTC, maiconpeixinho approved these changes

2021-05-21 10:46 UTC, merged